### ISSUE TITLE
Question: Does it still prevent mob from spawning near torch?

### ISSUE THREAD

**Issue by Maelep** [SmushyTaco/Daylight-Mobs-Reborn#1]
I really like the idea of disabling mob burn at sun and allowing them to spawn during day but I'm afraid to see a creeper spawn in my base... Does your plugin takes into account the artificial light? (from blocks and torches). If not, could you add this option so it can prevents mobs from spawning in your base because of artificial light.

**Comment by SmushyTaco** [comment]
It does
